/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatroom.server;

import java.awt.Toolkit;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 
 * @author kkapa
 */
public class ChatroomServer extends javax.swing.JFrame {
    //database variables
    /**
     * Zmienna przechowująca zapytania do bazy danych
     */
    Statement statement;
    /**
     * Zmienna przechowująca odnośnik do połączenia z bazą danych
     */
    Connection conn;
    /**
     * URL do bazy danych przechowującej informacje o czacie
     */
    String url = "jdbc:postgresql://localhost:5432/chatroom-db";
    /**
     * Stała przechowująca znak stopu między kolejnymi fragmentami przesyłanej informacji
     */
    static final String DELIMITER=";end;";
    /**
     * Zmienna przechowująca dane właściciela bazy danych, w celu pomyślnego zalogowania się do niej
     */
    static final String LOGIN="postgres",PASS="poszlaoladoprzedszkola";
    /**
     * Zmienna przechowująca listę strumieni wyjścia do klientów
     */
    ArrayList<User> users;
    /**
     * Klasa służąca wyłącznie do przesyłania e-maili
     */
    static MailSender sender=new MailSender();
    
    Table tab_users, messages, mutes;
    
    static final String MES_TAB="messages",MES_ID_COL="id",MES_COL="message",TIME_COL="sendtime",SEND_COL="username";
    //order: id, username, sendtime, message   
    /**
     * <p>Funkcja tworzy nowy formularz ChatroomServer, i wyśrodkowuje go na ekranie</p>
     * <p>Łączy się automatycznie z bazą danych i uruchamia wątek ServerStart zbierający
     * połączenia od użytkowników, lub informuje administratora o błędzie połączenia z bazą.
     * Jeśli połączenie się uda, guzik łączenia ręcznego się zdezaktywuje.</p>
     */
    public ChatroomServer() {
        initComponents();
        setToMiddle();
        Launch(); 
    }

    private void setToMiddle(){
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Launch = new javax.swing.JButton();
        ClientList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServerText = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(385, 505));

        Launch.setText("Uruchom ręcznie");
        Launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaunchActionPerformed(evt);
            }
        });

        ClientList.setText("Lista klientów");
        ClientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientListActionPerformed(evt);
            }
        });

        ServerText.setEditable(false);
        ServerText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ServerText.setText("...Serwer czeka na uruchomienie");
        jScrollPane1.setViewportView(ServerText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Launch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(ClientList)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientList)
                    .addComponent(Launch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Launch(){
        try{
        DbConnect();
        Launch.setEnabled(false);
        }catch (SQLException ex){
            ServerText.setText("Nie połączono z bazą.\nSpróbuj ponownie");
        }
            Thread starter = new Thread(new ServerStart(this));
            starter.start();
    }
    /**
     * <p>Służy do ręcznego połączenia z bazą danych oraz uruchomienia serwera,
     * jeżeli automatyczne połączenie się nie uda - mechanizm fail-safe.</p>
     * <p>Jeżeli połączenie się uda, guzik się zdezaktywuje. Po połączeniu z bazą 
     * uruchamiany jest wątek SerwerStart, zbierający połączenia od użytkowników.</p>
     * @param evt - nasłuchuje naciśnięcia guzika "Połącz manualnie"
     */
    private void LaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaunchActionPerformed
        Launch();
    }//GEN-LAST:event_LaunchActionPerformed

    private void ClientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientListActionPerformed
        String activeusers="";
        for(User temp: users){
            activeusers+=" "+temp.name;
        }
        ServerTextAppend("Aktywni klienci: "+activeusers);        // TODO add your handling code here:
    }//GEN-LAST:event_ClientListActionPerformed

    /**
     * @param args Nieużywany
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatroomServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChatroomServer().setVisible(true);
        });
    }

    /**
     * <p>Funkcja służy do łączenia z bazą danych.</p><p>
     * Wykorzystuje zmienne zadeklarowane wewnątrz programu: <b>URL, login, hasło</b>
     * aby wykonać połączenie. Gdy to się uda, administrator jest o tym informowany.</p>
     * <p>Funkcja stosowana jest w dwóch miejscach: w konstruktorze (automatyczne
     * połączenie) oraz wewnątrz funkcji LaunchActionPerformed (manualne połączenie)</p>
     * @throws SQLException jeżeli z jakiegokolwiek powodu połączenie się nie uda
     */
    
    private void DbConnect() throws SQLException{
        conn = DriverManager.getConnection(url,LOGIN,PASS);
        ServerText.setText("Połączono z bazą:\n"+url+"\n");
        InitializeDatabaseInfo();
    }
    
    private void InitializeDatabaseInfo() throws SQLException{
        ArrayList<Table> tables=GetAllTables();
        tables.forEach((temp) -> {
            try {
                GetAllColumns(temp);
            } catch (SQLException ex) {
                Logger.getLogger(ChatroomServer.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(null != ""+temp)switch (""+temp) {
                case "users":
                    tab_users=temp;
                    break;
                case "messages":
                    messages=temp;
                    break;
                case "mutes":
                    mutes=temp;
                    break;
                default:
                    break;
            }
        });
        
    }
    private ArrayList<Table> GetAllTables() throws SQLException{
        ArrayList<Table> tables=new ArrayList<>();
        ResultSet rs = conn.getMetaData().getTables("Chatroom", null, "%", null);
        while (rs.next()) {
          if (rs.getString(4)!=null && rs.getString(4).equalsIgnoreCase("TABLE")) {
                tables.add(new Table(rs.getString(3)));
            }
        }
        return tables;
    }
    private void GetAllColumns(Table table) throws SQLException{
        ResultSet rs = conn.createStatement().executeQuery("select * from "+table.name);
        ResultSetMetaData rsmd = rs.getMetaData();
        for(int i=1;i<=rsmd.getColumnCount();i++) table.addColumn(rsmd.getColumnName(i), rsmd.getColumnTypeName(i));
    }
    /**
     * <p> Funkcja służy do podpinania tekstu do panelu administratora.<p>
     * <p> Stosowana jest w klasach: ServerStart, ClientHandler, które nie mają
     * dostępu do prywatnych elementów klasy ChatroomServer.</p>
     * @param text - tekst do wyświetlenia na panelu administratora
     */
    public void ServerTextAppend(String text){
        ServerText.setText(ServerText.getText()+text);
        ServerText.setCaretPosition(ServerText.getDocument().getLength());
    }
    public void updateChat() throws SQLException{
        
        for(User temp:users){
            ResultSet rs=SelectFromChat(new String[]{messages.Get(0)+" IN (SELECT MAX("+messages.Get(0)+") FROM "+messages+")"},temp.name);
            
            while(rs.next()){
                temp.OS.println(String.join(DELIMITER,"Chat",rs.getTimestamp(messages.Get(2)).toString(),rs.getString(messages.Get(1)),"  "+rs.getString(messages.Get(3))));
                temp.OS.flush();
            }
        }
    }
    public void Insert(String table, String... values){
        String sql="INSERT INTO "+table+" VALUES("+String.join(", ",values)+");";
        updateDatabase(sql);
    }
    public void Delete(String table, String... conditions){
        String sql="DELETE FROM "+table+" WHERE ";
        sql+=String.join(" AND ",conditions);
        updateDatabase(sql);
    }
    public void Update(String table, String[] conditions, String... values){
        String sql="UPDATE "+table+" SET " + String.join(", ", values) + " WHERE "+String.join(" AND ",conditions)+";";
        updateDatabase(sql);
    }
    public ResultSet Select(String table, String[] conditions, String... columns){
        String sql="SELECT "+String.join(", ",columns)+" FROM "+table;
        if(conditions.length>0) sql+= " WHERE "+String.join(" AND ",conditions);
        sql+=";";
        System.out.println(sql);
        return queryDatabase(sql);
    }
    public ResultSet SelectFromChat(String[] conditions, String user){
        String[] newConditions=new String[conditions.length+1];
        for(int i=0;i<conditions.length;i++) newConditions[i]=conditions[i];
        newConditions[conditions.length]=messages.Get(1)+" NOT IN (SELECT "+mutes.Get(2)+" FROM "+mutes+" WHERE "+mutes.Get(1)+" = '"+user+"')";
        return Select(""+messages,newConditions,"*");
    }
    public Boolean CheckIn(String table, String[] conditions){
        try{
        return Select(table, conditions, "*").next();
        } catch (SQLException ex){
            ServerTextAppend("Błąd podczas sprawdzania bazy danych");
            return null;
        }
    }
    private void updateDatabase(String sql){
        int rs;
        try{
            System.out.println(sql);
        statement=conn.createStatement();
        rs=statement.executeUpdate(sql);
        }catch (SQLException ex){
            ServerTextAppend("Błąd w trakcie aktualizacji tabeli.");
        }
    }
    private ResultSet queryDatabase(String sql){
        try{
        statement=conn.createStatement();
        ResultSet rs=statement.executeQuery(sql);
        return rs;
        }catch (SQLException ex){
            ServerTextAppend("Błąd podczas wybierania wartości z bazy.");
        }
        return null;
    }
    
    public javax.swing.JTextPane getServerText(){
        return ServerText;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientList;
    private javax.swing.JButton Launch;
    private javax.swing.JTextPane ServerText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
